### ISSUE TITLE
High CPU Usage and Process Termination During Build

### ISSUE THREAD

**Issue by 4rdii** [nobitex/burnth#16] opened 2024-03-08 18:47 UTC
I encountered an issue while attempting to build the repository. After successfully installing the dependencies, I initiated the build process using the Makefile. However, the CPU usage suddenly spiked to 100%, and the process was terminated unexpectedly. The error message I received was as follows:
```
cd zk && make install
make[1]: Entering directory '/home/wsl/Security-Course/burnth/zk'
cd circuit && circom mpt_path.circom --r1cs --wasm --sym --c
template instances: 197
Killed
make[1]: *** [Makefile:9: circuit/mpt_path_cpp/mpt_path] Error 137
make[1]: Leaving directory '/home/wsl/Security-Course/burnth/zk'
make: *** [Makefile:4: build] Error 2
```
I would appreciate any assistance or guidance on how to resolve this issue.

**Comment by keyvank** [comment] 2024-03-10 10:46
Thanks for reporting, the issue is resolved in the latest commits!

**Closed by keyvank** 2024-03-10 10:46 UTC
